apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: v-1-2
  name: todo-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
